export type NacchinMasterEntry = {
  name: string;
  aliases: string[];
  reading: string;
  image: string;
  personality: string;
  relationship: string;
  love: string;
  usage: string;
  caution: string;
  sourceStatus: string;
  verificationStatus: string;
};

const nacchinMasterEntries: NacchinMasterEntry[] = [
  {
    name: "海中金性",
    aliases: ["海中金", "海中金（かいちゅうきん）"],
    reading: "かいちゅうきん",
    image: "海底に深く眠る砂金。誰かの力で引き上げられ、磨かれて光る質。",
    personality: "素晴らしい才能を秘めながら、表に出しすぎない控えめな性質。",
    relationship: "実力が過小評価されやすいので、理解者や引き立て役との縁が鍵になります。",
    love: "相手の言いなりになりすぎず、自分の望みを言葉にすることが大切です。",
    usage: "内側に眠る価値を磨く日。学び直し、作品整理、実績の棚卸し、信頼できる人への相談に向きます。",
    caution: "功を急ぐと結果が崩れやすいので、焦らず磨き込む姿勢を優先します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "炉中火性",
    aliases: ["炉中火", "炉中火（ろちゅうか）"],
    reading: "ろちゅうか",
    image: "いろりの中で燃える火。激しく燃え広がるより、場を温め続ける火の質。",
    personality: "内に秘めた激しい感情を、うまく制御していくタイプ。",
    relationship: "その場の雰囲気を和やかにするムードメーカーの性質があります。",
    love: "内側の情熱を隠しすぎず、穏やかに表へ出すことが大切です。",
    usage: "家、料理、サウナ、対話など、温度を整える行動に向きます。小さな場をあたためる日です。",
    caution: "軽挙妄動や異性問題で火が強くなりすぎないよう、温厚さを保ちます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "大林木性",
    aliases: ["大林木", "大林木（たいりんぼく）"],
    reading: "たいりんぼく",
    image: "生い茂る森林の中の一本の木。大きな場で競い合いながら伸びる質。",
    personality: "大胆さと繊細さの相反する気持ちを内包しています。",
    relationship: "幅広い人脈を作れますが、辛辣な発言には注意が必要です。",
    love: "奪い合うより、素直な気持ちで相手を愛する姿勢が運を整えます。",
    usage: "自然の中で深呼吸し、長期計画、人脈づくり、専門性の育成を進める日に向きます。",
    caution: "短気や負けず嫌いが強く出ると摩擦になります。温厚さと実直さを意識します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "路傍土性",
    aliases: ["路傍土", "路傍土（ろぼうど）"],
    reading: "ろぼうど",
    image: "道端の土。踏まれることで強く固まり、現実に根を張る質。",
    personality: "強固な意志と粘り強さに優れています。",
    relationship: "広く浅くより、深く長い付き合いを育てるタイプです。",
    love: "守りに入りやすく、関係がマンネリ化しやすい点に注意します。",
    usage: "散歩、現地確認、地道な作業、生活導線の見直しなど、足元を固める行動に向きます。",
    caution: "迷いや煩悶が出ても、急に方向転換せず、足元から一つずつ整えます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "剣鋒金性",
    aliases: ["剣鋒金", "劒鉾金", "劒(剣)鉾金", "劒(剣)鉾金（けんぼうきん）"],
    reading: "けんぼうきん",
    image: "剣や名刀の矛先。鋭い感覚と正義感を持つ金の質。",
    personality: "ものを見る目が鋭く、ひらめきに優れています。",
    relationship: "必要なときには相手にぶつかっていく強さがあります。",
    love: "クールに見えすぎると弊害が出るため、思いやりのある言葉が大切です。",
    usage: "判断、切り分け、整理、不要な縁や作業の見直しに向きます。",
    caution: "短気や争いを好む姿勢が出ると切れ味が傷になります。締めくくりを丁寧に。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "山頭火性",
    aliases: ["山頭火", "山頭火（さんとうか）"],
    reading: "さんとうか",
    image: "山頂で燃える火、くすぶる火山。高い理想や存在感を示す質。",
    personality: "火山のように理想を高く掲げる野心家の性質があります。",
    relationship: "慕われることも多い一方、敵もできやすいタイプです。",
    love: "片意地を張ると喧嘩別れになりやすいので、寛容さを意識します。",
    usage: "見晴らしのよい場所、発表、目標設定、理想の再確認に向く日です。",
    caution: "頭領の風格が強く出るほど、自重と寛容の精神が必要になります。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "澗下水性",
    aliases: ["澗下水", "潤下水", "潤下水（かんげんすい）"],
    reading: "かんげんすい",
    image: "岩の間から絶え間なく流れる水。少しずつ目標へ向かう質。",
    personality: "目標に向かって頑張り続ける努力の人です。",
    relationship: "年功序列より実力を重んじる傾向があります。",
    love: "強気一辺倒になりすぎると、せっかくの縁を流してしまうことがあります。",
    usage: "水分補給、温泉、デトックス、継続作業、少しずつ進める計画に向きます。",
    caution: "一気に進めようとすると崩れやすいので、実行力と信用を積み上げます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "城頭土性",
    aliases: ["城頭土", "城頭土（じょうとうど）"],
    reading: "じょうとうど",
    image: "城内の広大な土地。整えられた領域と高い自意識を示す土の質。",
    personality: "情に流されにくく、理想を守ろうとします。",
    relationship: "内面では敵味方や優劣を区別して付き合いやすい傾向があります。",
    love: "高い理想を持ち、厳しい目で相手を選びやすい質です。",
    usage: "境界線を整える日。家、仕事場、役割、契約範囲、守るべきものの確認に向きます。",
    caution: "プライドや自意識が強く出ると孤立します。融和を図ることが開運になります。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "白鑞金性",
    aliases: ["白鑞金", "白蝋金", "白蝋金（はくろうきん）"],
    reading: "はくろうきん",
    image: "精製された鉛と錫。柔らかく、相手に合わせられる金の質。",
    personality: "優しく従順な平和主義者の性質があります。",
    relationship: "断り下手で、損な役割を押し付けられやすい面があります。",
    love: "優柔不断に見える態度がネックになりやすいので、意思表示を整えます。",
    usage: "調整、仲介、道具の手入れ、身だしなみ、柔らかい交渉に向きます。",
    caution: "わがままや自尊心が出ると受け入れられにくくなります。誠意と円満を意識します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "楊柳木性",
    aliases: ["楊柳木", "揚柳木", "揚柳木（ようりゅうぼく）"],
    reading: "ようりゅうぼく",
    image: "柳の木。柳に風のように揺れ、水を好むしなやかな木の質。",
    personality: "柔らかな物腰で従順ですが、意思の弱さが出やすい面があります。",
    relationship: "第一印象は良い一方、場当たり的な対応になりすぎない注意が必要です。",
    love: "自分の気持ちを強く押し出すことも大切です。",
    usage: "散歩、水辺、香り、会話、柔らかい調整に向きます。流れに乗りつつ軸を確認する日です。",
    caution: "消極的になると発展が遅れます。明朗さと勇気を少し足します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "井泉水性",
    aliases: ["井泉水", "井泉水（いせんすい）"],
    reading: "いせんすい",
    image: "地下から絶え間なく湧き出る井戸水。純粋で惜しみなく与える水の質。",
    personality: "純粋で、金銭や物質への執着が薄い性分です。",
    relationship: "裏表がなく信じやすい反面、だまされやすさに注意が必要です。",
    love: "正直になりすぎて恋を失わないよう、言い方を整えます。",
    usage: "湧き水、神社の手水、寄付、知識共有、無償の親切に向きます。",
    caution: "狡猾さや虚言に巻き込まれないよう、純粋さと境界線を両立します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "屋上土性",
    aliases: ["屋上土", "屋上土（おくじょうど）"],
    reading: "おくじょうど",
    image: "屋根瓦の下に敷く土。防水し、上から全体を見る乾いた土の質。",
    personality: "冷静でドライ、合理的な考え方を持ちます。",
    relationship: "適度な距離を置きながら、広く浅い付き合いが得意です。",
    love: "クールな付き合いを望みすぎると、他人行儀になりがちです。",
    usage: "俯瞰、書類整理、防災、防水、住まいの点検、距離感の調整に向きます。",
    caution: "交際下手で損をしやすいため、人との和を図る意識を足します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "霹靂火性",
    aliases: ["霹靂火", "霹靂火（へきれきか）"],
    reading: "へきれきか",
    image: "突然激しく鳴り出す雷。瞬発力と衝撃を持つ火の質。",
    personality: "ずば抜けた瞬発力と集中力があります。",
    relationship: "激情型で、怒らせると怖い相手に見られやすい面があります。",
    love: "感情を抑えられないと、大切な縁を失いやすくなります。",
    usage: "短時間集中、突破、溜めた感情の発散、雷雨後のようなリセットに向きます。",
    caution: "強情さやわがままが出ると機会を失います。温情と協調を意識します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "松柏木性",
    aliases: ["松柏木", "松柏木（しょうはくぼく）"],
    reading: "しょうはくぼく",
    image: "松や柏などの常緑樹。冬でも緑を保ち、神の依代にもなる木の質。",
    personality: "困難を乗り越える強い精神力を持ちます。",
    relationship: "好き嫌いが二極化しやすい傾向があります。",
    love: "相手を思い続ける一途な恋に向きます。",
    usage: "神社参拝、長期継続、信念の確認、上へ伸びる学びに向きます。",
    caution: "気移りや疑い深さが幸運を逃すことがあります。信用を育てる姿勢を大切に。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "長流水性",
    aliases: ["長流水", "長流水（ちょうりゅうすい）"],
    reading: "ちょうりゅうすい",
    image: "長い川を流れていく水。太い水量で清濁を運ぶ水の質。",
    personality: "清濁併せ呑む大きな度量を持ちます。",
    relationship: "ときに激流のように感情が暴れることがあります。",
    love: "親しくなるほど、自分の意見を押し付けやすい面があります。",
    usage: "移動、川沿い、長期計画、浄化、情報や感情を流す行動に向きます。",
    caution: "高慢さや短気が争いにつながります。円満主義で流れを整えます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "沙中金性",
    aliases: ["沙中金", "沙中金（さちゅうきん）"],
    reading: "さちゅうきん",
    image: "砂の中に混ざった金。控えめで繊細、風で表情を変える金の質。",
    personality: "控えめながら個性豊かで、器用にこなせるタイプです。",
    relationship: "繊細で傷つきやすく、交友関係を狭めやすい面があります。",
    love: "待つだけでなく、自分から行動を起こすことも大切です。",
    usage: "小さな価値の発掘、買い物、会計確認、手仕事、繊細な調整に向きます。",
    caution: "短気や取り越し苦労で能率が落ちやすいので、情熱を一点に集めます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "山下火性",
    aliases: ["山下火"],
    reading: "さんげか",
    image: "山のふもとに宿る火。やる気があっても、時機や環境の助けを待つ火の質。",
    personality: "内側に意欲を持ち、機会を得ることで明るく動き出します。",
    relationship: "人のために尽くす心が、周囲からの後押しを呼びます。",
    love: "焦って燃え上がるより、相手の状況を見ながら温度を合わせます。",
    usage: "下準備、奉仕、応援を受ける相談、灯りをともすような小さな開始に向きます。",
    caution: "チャンスに恵まれない感覚が出ても、天恵を得る努力を続けます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "平地木性",
    aliases: ["平地木"],
    reading: "へいちぼく",
    image: "平らな土地に育つ木。地味で勤勉、生活の場で伸びる木の質。",
    personality: "直行努力型で、地道に積み上げる力があります。",
    relationship: "豪放な面と強情さが同居し、協調が課題になりやすい質です。",
    love: "相手の歩幅に合わせ、独断偏見をゆるめることが大切です。",
    usage: "生活改善、畑や庭、家族の用事、ルーティンの整備に向きます。",
    caution: "独断や強情さが出ると円滑さを欠きます。寛大な心が成功を呼びます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "壁上土性",
    aliases: ["壁上土"],
    reading: "へきじょうど",
    image: "壁の上の土。境界を作り、守り、内外を分ける土の質。",
    personality: "勤勉で内面的、細かいところまで気づく性質があります。",
    relationship: "人の和を乱さないよう、細部へのこだわりを調整することが大切です。",
    love: "守りを固めすぎると距離が生まれます。小さなこだわりを手放します。",
    usage: "壁、収納、境界、ルール、住まいの整備に向きます。",
    caution: "小さなことにこだわりすぎると失敗します。小を捨てて大きく整えます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "金箔金性",
    aliases: ["金箔金"],
    reading: "きんぱくきん",
    image: "薄く広がる金箔。華やかさと繊細さを同時に持つ金の質。",
    personality: "智謀や正義感があり、美しく見せる力を持ちます。",
    relationship: "独断専行や度を過ぎた正義感が摩擦になることがあります。",
    love: "華やかさを保ちながら、ほどほどの柔らかさを添えます。",
    usage: "装い、見せ方、広報、贈り物、場を美しく整える行動に向きます。",
    caution: "正しさを押し出しすぎると失敗につながります。ほどほどを意識します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "覆燈火性",
    aliases: ["覆燈火"],
    reading: "ふくとうか",
    image: "覆われた灯火。静かな場所で保たれる、落ち着いた火の質。",
    personality: "温厚で努力家、落ち着いた人柄を持ちます。",
    relationship: "生一本さや積極性の弱さが、機会を狭めることがあります。",
    love: "気持ちを隠しすぎず、目標を一つにして伝えることが大切です。",
    usage: "読書、祈り、集中、夜の作業、小さな灯りのような継続に向きます。",
    caution: "機敏性に乏しくなりやすいため、目標を一つに絞って動きます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "天河水性",
    aliases: ["天河水"],
    reading: "てんがすい",
    image: "天の川の水。明るさ、人情、広がりを持つ大きな水の質。",
    personality: "明朗快活で人に好かれ、大器晩成の気配があります。",
    relationship: "人情に厚く勤勉ですが、放漫さが出ると信用を落とします。",
    love: "大きく包み込みつつ、細やかな配慮を忘れないことが大切です。",
    usage: "旅、水辺、星空、広い場所、長期的な夢の確認に向きます。",
    caution: "散財や緻密さの欠如に注意し、流れを大きくしすぎないよう整えます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "大駅土性",
    aliases: ["大駅土", "大驛土"],
    reading: "たいえきど",
    image: "大きな駅や交通の要所の土。人と物が集まり動く土の質。",
    personality: "器用で才知に富み、福運と快活さがあります。",
    relationship: "人に好かれやすい一方、高慢さや大言壮語に注意が必要です。",
    love: "軽く扱う態度が誤解を生むため、相手への敬意を明確にします。",
    usage: "移動、駅、拠点確認、商談、複数の予定をつなぐ行動に向きます。",
    caution: "短気、非常識さ、他人への軽蔑が失敗の原因になります。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "釵釧金性",
    aliases: ["釵釧金"],
    reading: "さいせんきん",
    image: "かんざしや腕輪の金。身につける美と品位を表す金の質。",
    personality: "真面目で不器用ながら、仕事熱心で独自性があります。",
    relationship: "閉鎖的になりすぎると孤立しますが、独自分野の開拓に強みがあります。",
    love: "飾りすぎず、誠実さを見える形にすることが大切です。",
    usage: "装身具、身だしなみ、専門技術、手仕事、贈り物選びに向きます。",
    caution: "陰鬱さや極端な方向への変化に注意し、独自性を穏やかに活かします。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "桑柘木性",
    aliases: ["桑柘木"],
    reading: "そうしゃぼく",
    image: "桑や柘の木。暮らしと産業を支える、実用的な木の質。",
    personality: "商才があり、素直さと移り気が同居します。",
    relationship: "協力者に恵まれることで、後半から運が伸びやすい質です。",
    love: "口数の少なさや非常識に見える行動が誤解を生まないようにします。",
    usage: "商い、手仕事、衣食、生活を支える仕組みづくりに向きます。",
    caution: "移り気を抑え、協力者との信用を育てることが成功につながります。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "大渓水性",
    aliases: ["大渓水", "水渓水"],
    reading: "たいけいすい",
    image: "大きな谷川の水。勢いと深さを持つ水の質。",
    personality: "負けず嫌いで、温厚さの奥に強い意志があります。",
    relationship: "勝負事や色情に偏ると、円満さを欠きやすい面があります。",
    love: "小細工よりも、まっすぐな流れを作ることが大切です。",
    usage: "渓谷、温泉、浄化、集中した学び、感情の流れを整える行動に向きます。",
    caution: "勝ち負けにこだわりすぎず、円満さを保ちます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "沙中土性",
    aliases: ["沙中土"],
    reading: "さちゅうど",
    image: "砂の中の土。細やかで形を変えやすく、芸術性を含む土の質。",
    personality: "気位が高く、個性や芸術性が強く出ます。",
    relationship: "放言や高慢さが災いになりやすく、調和が大切です。",
    love: "個性を押し通すより、相手との円滑さを意識します。",
    usage: "砂浜、陶芸、アート、細やかな設計、形を整える作業に向きます。",
    caution: "円滑さを欠くと失敗しがちです。慎重さと調和を補います。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "天上火性",
    aliases: ["天上火"],
    reading: "てんじょうか",
    image: "天上に輝く火。高い場所から照らす、活発で明るい火の質。",
    personality: "活発な行動派で、思慮分別や慎重さも併せ持ちます。",
    relationship: "義理人情や独善性が強く出ると、損をしやすい面があります。",
    love: "自分の明るさで照らしつつ、相手の立場も尊重します。",
    usage: "発表、日の当たる場所、晴れの日の外出、目標を掲げる行動に向きます。",
    caution: "短気、傲慢心、義理人情での失敗に注意します。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "柘榴木性",
    aliases: ["柘榴木"],
    reading: "ざくろぼく",
    image: "柘榴の木。硬い殻の内側に多くの実を抱える木の質。",
    personality: "個性が強く、仕事に集中する力があります。",
    relationship: "神経質で感情の起伏が強く、協調が課題になりやすい質です。",
    love: "義理人情を重んじ、相手を裏切らない姿勢が運を整えます。",
    usage: "実りを分ける、作品づくり、集中仕事、種を残す行動に向きます。",
    caution: "感情の起伏や強すぎる個性が摩擦になります。協調の精神を大切に。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
  {
    name: "大海水性",
    aliases: ["大海水"],
    reading: "たいかいすい",
    image: "大きな海の水。広大で、慈悲と深さを持つ水の質。",
    personality: "高潔で慈悲心があり、才気に富む善良さがあります。",
    relationship: "自己暗示や自己中心的な行動が失敗につながることがあります。",
    love: "情に流されすぎず、誠実な距離感を保つことが大切です。",
    usage: "海、旅、祈り、大きな浄化、人生の視野を広げる行動に向きます。",
    caution: "色情、狂言的な傾向、自己中心性に注意し、反省と謙虚さを持ちます。",
    sourceStatus: "spreadsheet:納音!A1:J61",
    verificationStatus: "pending_text_review",
  },
];

function normalizeNacchinName(value: string) {
  return value
    .replace(/[（）()]/g, "")
    .replace(/性$/g, "")
    .replace(/劒/g, "剣")
    .replace(/剱/g, "剣")
    .replace(/鉾/g, "鋒")
    .replace(/白蝋/g, "白鑞")
    .replace(/揚柳/g, "楊柳")
    .replace(/潤下/g, "澗下")
    .replace(/水渓/g, "大渓")
    .replace(/大驛/g, "大駅")
    .replace(/佛/g, "仏")
    .replace(/（.*?）/g, "")
    .trim();
}

export function getNacchinMasterEntries() {
  return nacchinMasterEntries;
}

export function getNacchinMasterEntry(name: string) {
  const normalized = normalizeNacchinName(name);

  return (
    nacchinMasterEntries.find((entry) => {
      const names = [entry.name, ...entry.aliases];

      return names.some((candidate) => normalizeNacchinName(candidate) === normalized);
    }) ?? null
  );
}
