import type {
  BoundaryRuleDefinition,
  ConflictRecord,
  FutureRuleReference,
  ImplementationBinding,
  ImplementationGap,
  ImplementationObservation,
  LineageContext,
  ProhibitedInference,
  ProjectClaim,
  RuleDefinition,
  SourceClaim,
  TechniqueDefinition,
  VerificationRecord,
  WorkflowAggregateDefinition,
} from "@/lib/divination-provenance/types";

export const personalStarSourceClaims = [
  {
    claimId: "source-claim.sonoda-1934.honmei-birth-center.v1",
    sourceClaimVersion: "1",
    sourceId: "source.sonoda.kaisei-hoi-meikan.1934.ed4",
    sourceType: "historical_calendar",
    claimType: "source_fact",
    summary: "園田1934年資料では、出生時に中宮する年星を人物の本命として扱う。",
    sourceVerificationStatus: "confirmed_for_named_lineage",
    materialType: "book",
    bodyContentVerified: true,
    pageOrRange: "本文p.7相当",
    notes: ["園田系統について確認済みであり、全流派共通とはしない。"],
  },
  {
    claimId: "source-claim.sonoda-1934.risshun-timestamp-boundary.v1",
    sourceClaimVersion: "1",
    sourceId: "source.sonoda.kaisei-hoi-meikan.1934.ed4",
    sourceType: "historical_calendar",
    claimType: "source_fact",
    summary: "園田1934年資料では、立春時刻の前後で出生年の採用区分を分ける。",
    sourceVerificationStatus: "confirmed_for_named_lineage",
    materialType: "book",
    bodyContentVerified: true,
    pageOrRange: "本文p.8相当",
    notes: ["exact Risshun境界のproject採用・production接続とは別claim。"],
  },
  {
    claimId: "source-claim.jingukan-1935.annual-nine-star-cycle.v1",
    sourceClaimVersion: "1",
    sourceId: "source.jingukan.kyusei-rekijutsu.1935",
    sourceType: "historical_calendar",
    claimType: "calculation_rule",
    summary: "神宮館1935年資料は年家九星を循環で決定する。",
    sourceVerificationStatus: "confirmed",
    materialType: "book",
    bodyContentVerified: true,
    pageOrRange: "年家九星起例付近",
    notes: ["西暦数字和の簡略式まで同資料で確認したことにはしない。"],
  },
  {
    claimId: "source-claim.jingukan-1935.monthly-nine-star-36.v1",
    sourceClaimVersion: "1",
    sourceId: "source.jingukan.kyusei-rekijutsu.1935",
    sourceType: "historical_calendar",
    claimType: "calculation_rule",
    summary: "神宮館1935年資料は3年支群ごとに12月の月家九星系列を割り当てる。",
    sourceVerificationStatus: "confirmed",
    materialType: "book",
    bodyContentVerified: true,
    pageOrRange: "本文p.15〜16相当",
    notes: ["月命星という現代的人物roleは別claim。"],
  },
  {
    claimId: "source-claim.jingukan-1935.monthly-setsu-boundary.v1",
    sourceClaimVersion: "1",
    sourceId: "source.jingukan.kyusei-rekijutsu.1935",
    sourceType: "historical_calendar",
    claimType: "source_fact",
    summary: "月家九星は朔日ではなく12節の節替りで交替する。",
    sourceVerificationStatus: "confirmed",
    materialType: "book",
    bodyContentVerified: true,
    pageOrRange: "本文p.16相当",
    notes: ["全12節のexact timestampはpartially_confirmedのまま。"],
  },
  {
    claimId: "source-claim.tomihisa-institutional.getsumei-personal-role.v1",
    sourceClaimVersion: "1",
    sourceId: "source.toyo-unseigakkai.keisha-part1.tomihisa",
    sourceType: "institutional_specialist_source",
    claimType: "source_fact",
    summary: "東洋運勢学会の記事は月命星を生月を支配する生まれ星として人物判断へ用いる。",
    sourceVerificationStatus: "partially_confirmed",
    materialType: "institutional_specialist_article",
    institution: "一般財団法人 東洋運勢学会",
    lineageRelevance: "trusted_for_project",
    bodyContentVerified: true,
    pageOrRange: "第20回 気学傾斜法 前編 1/3",
    notes: ["記事本文で確認できたclaimだけを対象とする。"],
  },
  {
    claimId: "source-claim.tomihisa-institutional.getsumei-keisha-table.v1",
    sourceClaimVersion: "1",
    sourceId: "source.toyo-unseigakkai.keisha-part1.tomihisa",
    sourceType: "institutional_specialist_source",
    claimType: "source_fact",
    summary: "東洋運勢学会の記事は本命星と月命星の組合せを月盤・傾斜宮の108入力相当表で示す。",
    sourceVerificationStatus: "partially_confirmed",
    materialType: "institutional_specialist_article",
    institution: "一般財団法人 東洋運勢学会",
    lineageRelevance: "trusted_for_project",
    bodyContentVerified: true,
    pageOrRange: "第20回 気学傾斜法 前編 2/3 表1",
    notes: ["傾斜のexecutable Ruleまたは流派選択には接続しない。"],
  },
  {
    claimId: "source-claim.tomihisa-2000.keisha-book-scope.v1",
    sourceClaimVersion: "1",
    sourceId: "source.tomihisa.keisha-hiho.2000",
    sourceType: "modern_reference",
    claimType: "bibliographic_scope",
    summary: "富久純光『修訂気学傾斜秘法』の書誌・目次は月盤表、傾斜法、本命星・月命星を対象に含む。",
    sourceVerificationStatus: "partially_confirmed",
    materialType: "book",
    lineageRelevance: "trusted_for_project",
    bodyContentVerified: false,
    notes: ["目次から本文規則を生成しない。"],
  },
  {
    claimId: "source-claim.kumokiri.monthly-exact-setsu-boundary.v1",
    sourceClaimVersion: "1",
    sourceId: "source.kumokiri.honmei-getsumei-web",
    sourceType: "modern_reference",
    claimType: "calculation_rule",
    summary: "記名実務資料は12月の節入り時刻表と節入り前後で月命星が変わる例を示す。",
    sourceVerificationStatus: "partially_confirmed",
    notes: ["独立専門書本文による全12節確認には置き換えない。"],
  },
  {
    claimId: "source-claim.ptna-2017.getsumei-boundary-example.v1",
    sourceClaimVersion: "1",
    sourceId: "source.ptna.kyusei.getsumei.2017",
    sourceType: "modern_reference",
    claimType: "interpretation",
    summary: "現代記事は節入り当日の時刻前を前月の九星として扱う例を示す。",
    sourceVerificationStatus: "partially_confirmed",
    notes: ["自然時補正への言及はprojectのassumed JSTと別variant。"],
  },
  {
    claimId: "source-claim.getsumei-time-basis-variants.v1",
    sourceClaimVersion: "1",
    sourceId: "source-research.getsumei-time-basis",
    sourceType: "project_research_ledger",
    claimType: "interpretation",
    summary: "月命星境界にはstandard JSTとlocal natural time correctionの方式差がある。",
    sourceVerificationStatus: "conflict",
    notes: ["資料差をsource typeや自動weightで解決しない。"],
  },
] as const satisfies readonly SourceClaim[];

export const personalStarLineageContexts = [
  {
    lineageContextId: "lineage-context.tomihisa-keisha.v1",
    lineageContextVersion: "1",
    subjectIds: [
      "source.toyo-unseigakkai.keisha-part1.tomihisa",
      "source.tomihisa.keisha-hiho.2000",
    ],
    status: "po_confirmed_lineage_context",
    summary: "富久純光系統を本プロジェクトの月命星・傾斜法研究で優先する重要専門系譜として扱う。",
    relatedSourceIds: [
      "source.toyo-unseigakkai.keisha-part1.tomihisa",
      "source.tomihisa.keisha-hiho.2000",
    ],
    relatedSourceClaimIds: [
      "source-claim.tomihisa-institutional.getsumei-personal-role.v1",
      "source-claim.tomihisa-institutional.getsumei-keisha-table.v1",
      "source-claim.tomihisa-2000.keisha-book-scope.v1",
    ],
    doesNotAssert: [
      "富久純光氏の国籍",
      "傾斜法を最初に発明した人物であること",
      "未確認書籍本文の内容",
      "東洋運勢学会全体の未記載見解",
    ],
  },
] as const satisfies readonly LineageContext[];

export const personalStarProjectClaims = [
  {
    claimId: "project-claim.personal-star-scope.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "個人星provenanceを本命星・月命星の静的定義、lookup、role binding、traceへ限定する。",
    projectAdoptionStatus: "adopted",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [
      "source-claim.sonoda-1934.honmei-birth-center.v1",
      "source-claim.jingukan-1935.monthly-nine-star-36.v1",
    ],
  },
  {
    claimId: "project-claim.honmei-boundary-at-risshun.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "本命星の精密境界を正確なJST立春時刻とする候補方針。",
    projectAdoptionStatus: "provisional",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [
      "source-claim.sonoda-1934.risshun-timestamp-boundary.v1",
      "source-claim.solar-term-timestamps.v1",
    ],
  },
  {
    claimId: "project-claim.getsumei-boundary-at-setsuiri.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "月命星の精密境界を12節の正確なJST節入り時刻とする候補方針。",
    projectAdoptionStatus: "provisional",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [
      "source-claim.jingukan-1935.monthly-setsu-boundary.v1",
      "source-claim.kumokiri.monthly-exact-setsu-boundary.v1",
      "source-claim.ptna-2017.getsumei-boundary-example.v1",
      "source-claim.solar-term-timestamps.v1",
    ],
  },
  {
    claimId: "project-claim.getsumei-role-binding.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "出生月の月家九星を人物属性として固定し、月命星という別役割のTechniqueにする。",
    projectAdoptionStatus: "adopted",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [
      "source-claim.jingukan-1935.monthly-nine-star-36.v1",
      "source-claim.tomihisa-institutional.getsumei-personal-role.v1",
    ],
  },
  {
    claimId: "project-claim.personal-stars-assumed-jst.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "timezone未指定時はJSTを仮定するが、唯一の占術上のsource truthとはしない。",
    projectAdoptionStatus: "provisional",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: ["source-claim.getsumei-time-basis-variants.v1"],
  },
  {
    claimId: "project-claim.personal-stars-unresolved-input-policy.v1",
    projectClaimVersion: "1",
    claimType: "po_specification",
    summary: "境界日に出生時刻が不明ならexact resultをunresolvedとしfallback星を作らない。",
    projectAdoptionStatus: "adopted",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [],
  },
  {
    claimId: "project-claim.personal-star-workflow-effect-free.v1",
    projectClaimVersion: "1",
    claimType: "application_policy",
    summary: "個人星workflowは吉凶効果、加点、candidate、ranking、warningを持たない。",
    projectAdoptionStatus: "adopted",
    productionConnectionStatus: "not_connected",
    relatedSourceClaimIds: [],
  },
] as const satisfies readonly ProjectClaim[];

export const personalStarImplementationBindings = [
  {
    bindingId: "implementation.personal.daily-master.v1",
    techniqueIds: [
      "birth-year-period-resolution",
      "birth-month-period-resolution",
      "honmei-star-resolution",
      "getsumei-star-resolution",
    ],
    sourceFiles: [
      "src/lib/calendar-master-rows.ts",
      "src/lib/calendar-day.ts",
      "src/data/calendar-master/by-year/{year}.json",
    ],
    functions: ["getCalendarMasterRow", "getCalendarDays"],
    masterColumns: ["duplicateYear", "duplicateMonth", "yearKyusei", "monthKyusei"],
    tests: ["src/lib/getsumei-regression.test.ts"],
    currentBehaviorSummary: "birthDateのdaily master行を終日同一の年星・月星として使用する。",
    implementationResolution: "date",
    exactTimestampSupport: false,
  },
  {
    bindingId: "implementation.personal.calendar-db-context.v1",
    techniqueIds: ["honmei-star-resolution"],
    sourceFiles: ["src/lib/calendar-db-view.ts"],
    functions: ["getPersonalContext", "getPersonalContextFromHonmeiStar"],
    masterColumns: [],
    tests: [],
    currentBehaviorSummary: "private関数が出生日行のyearKyuseiをhonmeiStarへ結び付ける。",
  },
  {
    bindingId: "implementation.personal.keisha-profile.v1",
    techniqueIds: ["getsumei-star-resolution"],
    sourceFiles: ["src/lib/calendar-db-view.ts", "src/lib/keisha-master.ts"],
    functions: ["buildPersonalProfile", "getKeishaProfile"],
    masterColumns: ["monthKyusei"],
    tests: ["src/lib/getsumei-regression.test.ts"],
    currentBehaviorSummary: "monthKyuseiをgetsumeiStar引数へ渡す既存binding。傾斜Ruleは本registryの実装対象外。",
  },
] as const satisfies readonly ImplementationBinding[];

export const personalStarBoundaryRules = [
  {
    boundaryRuleId: "boundary.personal-input-date-resolution.v1",
    boundaryVersion: "1",
    label: "個人星入力の日付・出生時刻精度",
    boundaryType: "personal_input",
    precisionStatus: "partially_confirmed",
    effectiveResolution: "second",
    exactTimestampSupport: true,
    exactTimestampSupportScope: "schema_and_trace_only",
    timezonePolicy: "timezone未指定はassumed_jst。birthTime不明は時刻を補完しない。",
    sourceClaimIds: [],
    projectClaimIds: [
      "project-claim.personal-stars-assumed-jst.v1",
      "project-claim.personal-stars-unresolved-input-policy.v1",
    ],
    implementationBindingIds: ["implementation.personal.daily-master.v1"],
    ruleSummary: "入力精度をdate_onlyまたはexact timestampとして保持する。",
    unresolvedIssues: ["海外出生、DST、経度補正、真太陽時、均時差は未対応。"],
  },
  {
    boundaryRuleId: "boundary.honmei-risshun-timestamp.v1",
    boundaryVersion: "1",
    label: "本命星の立春時刻年界",
    boundaryType: "risshun_year",
    precisionStatus: "exact_timestamp_confirmed",
    effectiveResolution: "second",
    exactTimestampSupport: true,
    exactTimestampSupportScope: "schema_and_trace_only",
    timezonePolicy: "assumed_jst",
    sourceVerificationStatus: "confirmed_for_named_lineage",
    projectAdoptionStatus: "provisional",
    productionConnectionStatus: "not_connected",
    sourceClaimIds: [
      "source-claim.sonoda-1934.risshun-timestamp-boundary.v1",
      "source-claim.solar-term-timestamps.v1",
    ],
    projectClaimIds: ["project-claim.honmei-boundary-at-risshun.v1"],
    implementationBindingIds: ["implementation.solar-term.verified-master.v1"],
    ruleSummary: "園田系統のsource laneでは立春時刻前後で採用年を切り替える。",
    unresolvedIssues: ["全流派共通claimではない。", "productionへ接続しない。"],
  },
  {
    boundaryRuleId: "boundary.getsumei-setsuiri-timestamp.v1",
    boundaryVersion: "1",
    label: "月命星の12節時刻月界",
    boundaryType: "setsuiri_month",
    precisionStatus: "partially_confirmed",
    effectiveResolution: "second",
    exactTimestampSupport: true,
    exactTimestampSupportScope: "schema_and_trace_only",
    timezonePolicy: "assumed_jst",
    sourceVerificationStatus: "partially_confirmed",
    projectAdoptionStatus: "provisional",
    productionConnectionStatus: "not_connected",
    sourceClaimIds: [
      "source-claim.jingukan-1935.monthly-setsu-boundary.v1",
      "source-claim.kumokiri.monthly-exact-setsu-boundary.v1",
      "source-claim.ptna-2017.getsumei-boundary-example.v1",
      "source-claim.solar-term-timestamps.v1",
    ],
    projectClaimIds: ["project-claim.getsumei-boundary-at-setsuiri.v1"],
    implementationBindingIds: ["implementation.solar-term.verified-master.v1"],
    ruleSummary: "schema・trace上で12節の秒精度境界候補を表現する。",
    unresolvedIssues: ["全12節exact timestampの専門書本文確認は未完了。", "productionへ接続しない。"],
  },
  {
    boundaryRuleId: "boundary.personal-daily-master-resolution.v1",
    boundaryVersion: "1",
    label: "現行個人星daily master境界",
    boundaryType: "implementation_resolution",
    precisionStatus: "implementation_observed",
    effectiveResolution: "date",
    implementationResolution: "date",
    exactTimestampSupport: false,
    timezonePolicy: "date key only; birthTime・timezoneは未使用",
    productionConnectionStatus: "existing_date_binding",
    sourceClaimIds: [],
    projectClaimIds: [],
    implementationBindingIds: ["implementation.personal.daily-master.v1"],
    ruleSummary: "現行productionは出生日のdaily master値を終日使用する。",
    unresolvedIssues: ["立春1件、月節6件の翌日切替理由は未解決。"],
  },
] as const satisfies readonly BoundaryRuleDefinition[];

const step = (
  stepId: string,
  label: string,
  operation: "lookup" | "date_boundary" | "normalization" | "role_binding",
  ruleId: string,
  inputFieldIds: readonly string[],
  outputFieldIds: readonly string[],
) => ({
  stepId,
  label,
  inputFieldIds,
  operation,
  ruleReferenceIds: [ruleId],
  outputFieldIds,
});

export const personalStarRules = [
  { ruleId: "rule.personal.birth-datetime-normalization.v1", ruleVersion: "1", techniqueId: "birth-datetime-normalization", status: "partially_confirmed", inputFieldIds: ["birthDate", "birthTime", "timezone"], outputFieldIds: ["birthDatetimeJst", "inputPrecision", "timezoneStatus"], boundaryRuleIds: ["boundary.jst-normalization.v1", "boundary.personal-input-date-resolution.v1"], sourceClaimIds: [], projectClaimIds: ["project-claim.personal-stars-assumed-jst.v1", "project-claim.personal-stars-unresolved-input-policy.v1"], lookupTableIds: [], derivationSteps: [step("personal-birth-normalization", "出生入力と精度を正規化", "normalization", "rule.personal.birth-datetime-normalization.v1", ["birthDate", "birthTime", "timezone"], ["birthDatetimeJst", "inputPrecision", "timezoneStatus"])] },
  { ruleId: "rule.personal.birth-year-period-resolution.v1", ruleVersion: "1", techniqueId: "birth-year-period-resolution", status: "partially_confirmed", inputFieldIds: ["birthDatetimeJst", "inputPrecision"], outputFieldIds: ["adoptedYear"], boundaryRuleIds: ["boundary.honmei-risshun-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], sourceClaimIds: ["source-claim.sonoda-1934.risshun-timestamp-boundary.v1", "source-claim.solar-term-timestamps.v1"], projectClaimIds: ["project-claim.honmei-boundary-at-risshun.v1"], lookupTableIds: [], derivationSteps: [step("personal-year-boundary", "立春境界から採用年を決定", "date_boundary", "rule.personal.birth-year-period-resolution.v1", ["birthDatetimeJst", "inputPrecision"], ["adoptedYear"])] },
  { ruleId: "rule.personal.birth-month-period-resolution.v1", ruleVersion: "1", techniqueId: "birth-month-period-resolution", status: "partially_confirmed", inputFieldIds: ["birthDatetimeJst", "inputPrecision"], outputFieldIds: ["adoptedSetsuMonthBranch"], boundaryRuleIds: ["boundary.getsumei-setsuiri-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], sourceClaimIds: ["source-claim.jingukan-1935.monthly-setsu-boundary.v1", "source-claim.solar-term-timestamps.v1"], projectClaimIds: ["project-claim.getsumei-boundary-at-setsuiri.v1"], lookupTableIds: [], derivationSteps: [step("personal-month-boundary", "12節境界から採用月支を決定", "date_boundary", "rule.personal.birth-month-period-resolution.v1", ["birthDatetimeJst", "inputPrecision"], ["adoptedSetsuMonthBranch"])] },
  { ruleId: "rule.personal.year-nine-star-cycle.v1", ruleVersion: "1", techniqueId: "honmei-star-resolution", status: "table_confirmed", inputFieldIds: ["adoptedYear"], outputFieldIds: ["annualNineStar"], boundaryRuleIds: [], sourceClaimIds: ["source-claim.jingukan-1935.annual-nine-star-cycle.v1"], projectClaimIds: ["project-claim.personal-star-scope.v1"], lookupTableIds: ["lookup.personal.annual-nine-star-cycle.v1"], derivationSteps: [step("personal-annual-nine-star", "採用年から年家九星を参照", "lookup", "rule.personal.year-nine-star-cycle.v1", ["adoptedYear"], ["annualNineStar"])] },
  { ruleId: "rule.personal.honmei-from-adopted-year-star.v1", ruleVersion: "1", techniqueId: "honmei-star-resolution", status: "partially_confirmed", inputFieldIds: ["annualNineStar"], outputFieldIds: ["honmeiStar"], boundaryRuleIds: [], sourceClaimIds: ["source-claim.sonoda-1934.honmei-birth-center.v1"], projectClaimIds: ["project-claim.personal-star-scope.v1"], lookupTableIds: [], derivationSteps: [step("personal-honmei-role-binding", "年家九星を人物本命へ固定", "role_binding", "rule.personal.honmei-from-adopted-year-star.v1", ["annualNineStar"], ["honmeiStar"])] },
  { ruleId: "rule.personal.getsumei-from-year-group-and-setsu-month.v1", ruleVersion: "1", techniqueId: "getsumei-star-resolution", status: "table_confirmed", inputFieldIds: ["adoptedYearBranchGroup", "adoptedSetsuMonthBranch"], outputFieldIds: ["monthlyPlateCenterStar"], boundaryRuleIds: ["boundary.getsumei-setsuiri-timestamp.v1"], sourceClaimIds: ["source-claim.jingukan-1935.monthly-nine-star-36.v1"], projectClaimIds: ["project-claim.getsumei-role-binding.v1"], lookupTableIds: ["lookup.personal.getsumei-year-groups.v1", "lookup.personal.getsumei-36.v1"], derivationSteps: [step("personal-getsumei-lookup", "年groupと節月から月家九星を参照", "lookup", "rule.personal.getsumei-from-year-group-and-setsu-month.v1", ["adoptedYearBranchGroup", "adoptedSetsuMonthBranch"], ["monthlyPlateCenterStar"])] },
  { ruleId: "rule.personal.getsumei-role-binding.v1", ruleVersion: "1", techniqueId: "getsumei-star-resolution", status: "partially_confirmed", inputFieldIds: ["monthlyPlateCenterStar"], outputFieldIds: ["getsumeiStar"], boundaryRuleIds: [], sourceClaimIds: ["source-claim.tomihisa-institutional.getsumei-personal-role.v1"], projectClaimIds: ["project-claim.getsumei-role-binding.v1"], lookupTableIds: [], derivationSteps: [step("personal-getsumei-role-binding", "出生月の月家九星を人物属性へ固定", "role_binding", "rule.personal.getsumei-role-binding.v1", ["monthlyPlateCenterStar"], ["getsumeiStar"])] },
] as const satisfies readonly RuleDefinition[];

export const personalStarFutureRuleReferences = [
  {
    ruleId: "rule.personal.keisha-from-honmei-and-getsumei.v1",
    status: "hold",
    registeredAsExecutableRule: false,
    summary: "本命星と月命星から傾斜を求めるRuleは将来候補。既存傾斜productionを変更しない。",
  },
] as const satisfies readonly FutureRuleReference[];

const prohibitedInferenceIds = [
  "prohibit.personal.po-lineage-as-book-content",
  "prohibit.personal.institution-unwritten-position",
  "prohibit.personal.toc-as-body-rule",
  "prohibit.personal.tomihisa-biography-guess",
  "prohibit.personal.implementation-as-source",
  "prohibit.personal.annual-plate-honmei-merge",
  "prohibit.personal.monthly-plate-getsumei-merge",
  "prohibit.personal.birth-time-fallback",
  "prohibit.personal.daily-master-as-exact",
  "prohibit.personal.assumed-jst-as-only-truth",
  "prohibit.personal.natural-time-auto-implementation",
  "prohibit.personal.exact-boundary-production-connect",
  "prohibit.personal.keisha-lineage-choice",
  "prohibit.personal.getsumei-satsu-connect",
  "prohibit.personal.application-connect",
  "prohibit.personal.institutional-source-auto-resolve",
  "prohibit.personal.source-type-score",
  "prohibit.personal.lineage-context-as-source-claim",
  "prohibit.personal.ready-limited-as-production-ready",
] as const;

export const personalStarTechniques = [
  { techniqueId: "birth-datetime-normalization", techniqueVersion: "1", label: "出生日時入力正規化", domain: "calendar", sourceClaimIds: [], projectClaimIds: ["project-claim.personal-stars-assumed-jst.v1", "project-claim.personal-stars-unresolved-input-policy.v1"], ruleIds: ["rule.personal.birth-datetime-normalization.v1"], boundaryRuleIds: ["boundary.jst-normalization.v1", "boundary.personal-input-date-resolution.v1"], implementationBindingIds: ["implementation.personal.daily-master.v1"], dependencyTechniqueIds: [], applicationPolicyIds: [], prohibitedInferenceIds },
  { techniqueId: "birth-year-period-resolution", techniqueVersion: "1", label: "出生年期間決定", domain: "calendar", sourceClaimIds: ["source-claim.sonoda-1934.risshun-timestamp-boundary.v1", "source-claim.solar-term-timestamps.v1"], projectClaimIds: ["project-claim.honmei-boundary-at-risshun.v1"], ruleIds: ["rule.personal.birth-year-period-resolution.v1"], boundaryRuleIds: ["boundary.honmei-risshun-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], implementationBindingIds: ["implementation.personal.daily-master.v1", "implementation.solar-term.verified-master.v1"], dependencyTechniqueIds: ["birth-datetime-normalization"], applicationPolicyIds: [], prohibitedInferenceIds },
  { techniqueId: "birth-month-period-resolution", techniqueVersion: "1", label: "出生節月期間決定", domain: "calendar", sourceClaimIds: ["source-claim.jingukan-1935.monthly-setsu-boundary.v1", "source-claim.solar-term-timestamps.v1"], projectClaimIds: ["project-claim.getsumei-boundary-at-setsuiri.v1"], ruleIds: ["rule.personal.birth-month-period-resolution.v1"], boundaryRuleIds: ["boundary.getsumei-setsuiri-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], implementationBindingIds: ["implementation.personal.daily-master.v1", "implementation.solar-term.verified-master.v1"], dependencyTechniqueIds: ["birth-datetime-normalization"], applicationPolicyIds: [], prohibitedInferenceIds },
  { techniqueId: "honmei-star-resolution", techniqueVersion: "1", label: "本命星人物属性決定", domain: "nine_star", sourceClaimIds: ["source-claim.sonoda-1934.honmei-birth-center.v1", "source-claim.jingukan-1935.annual-nine-star-cycle.v1"], projectClaimIds: ["project-claim.personal-star-scope.v1"], ruleIds: ["rule.personal.year-nine-star-cycle.v1", "rule.personal.honmei-from-adopted-year-star.v1"], boundaryRuleIds: ["boundary.honmei-risshun-timestamp.v1"], implementationBindingIds: ["implementation.personal.daily-master.v1", "implementation.personal.calendar-db-context.v1"], dependencyTechniqueIds: ["birth-datetime-normalization", "birth-year-period-resolution"], applicationPolicyIds: [], prohibitedInferenceIds },
  { techniqueId: "getsumei-star-resolution", techniqueVersion: "1", label: "月命星人物属性決定", domain: "nine_star", sourceClaimIds: ["source-claim.jingukan-1935.monthly-nine-star-36.v1", "source-claim.tomihisa-institutional.getsumei-personal-role.v1"], projectClaimIds: ["project-claim.getsumei-role-binding.v1"], ruleIds: ["rule.personal.getsumei-from-year-group-and-setsu-month.v1", "rule.personal.getsumei-role-binding.v1"], boundaryRuleIds: ["boundary.getsumei-setsuiri-timestamp.v1"], implementationBindingIds: ["implementation.personal.daily-master.v1", "implementation.personal.keisha-profile.v1"], dependencyTechniqueIds: ["birth-datetime-normalization", "birth-year-period-resolution", "birth-month-period-resolution"], applicationPolicyIds: [], prohibitedInferenceIds },
] as const satisfies readonly TechniqueDefinition[];

export const personalStarWorkflow = {
  workflowId: "personal-star-profile-workflow",
  workflowVersion: "1",
  label: "本命星・月命星provenance workflow",
  techniqueIds: personalStarTechniques.map(({ techniqueId }) => techniqueId),
  applicationPolicyIds: [],
  effectType: "none",
  candidateConnected: false,
  rankingConnected: false,
  warningConnected: false,
  resultFieldIds: [
    "adoptedYear",
    "annualNineStar",
    "honmeiStar",
    "adoptedYearBranchGroup",
    "adoptedSetsuMonthBranch",
    "monthlyPlateCenterStar",
    "getsumeiStar",
  ],
} as const satisfies WorkflowAggregateDefinition;

const prohibitedSummaries = [
  "PO系譜評価を書籍本文確認済みclaimへ変換しない。",
  "記事未記載事項を東洋運勢学会の見解として補完しない。",
  "書籍目次から本文規則を生成しない。",
  "富久純光氏の国籍・傾斜法発明者性を推測しない。",
  "existing implementationをsource evidenceにしない。",
  "年盤中宮星と本命星のTechniqueを統合しない。",
  "月盤中宮星と月命星のTechniqueを統合しない。",
  "birthTime不明時に時刻またはfallback星を補完しない。",
  "daily master値をexact resultと呼ばない。",
  "assumed JSTを唯一の占術上の正解としない。",
  "自然時・経度・DST・真太陽時・均時差を推測実装しない。",
  "exact timestamp境界をproductionへ自動接続しない。",
  "傾斜計算または中宮傾斜の流派を選択しない。",
  "月命殺・月命的殺へ接続しない。",
  "candidate・ranking・warning・UI・APIへ接続しない。",
  "institutional_specialist_sourceを理由にconflictを自動解決しない。",
  "source typeから数値scoreを自動生成しない。",
  "lineage contextをsource claimとして利用しない。",
  "READY_WITH_LIMITATIONSをproduction-readyと解釈しない。",
] as const;

export const personalStarProhibitedInferences = prohibitedInferenceIds.map(
  (prohibitedInferenceId, index) => ({
    prohibitedInferenceId,
    summary: prohibitedSummaries[index]!,
  }),
) satisfies readonly ProhibitedInference[];

export const personalStarTimeBasisConflicts = [
  {
    conflictId: "conflict.personal-stars.time-basis.v1",
    conflictVersion: "1",
    status: "conflicting",
    summary: "月命星境界の時刻基準にstandard JSTとlocal natural time correctionの資料差がある。",
    variants: ["standard_jst", "local_natural_time_correction"],
    projectCurrentSelection: {
      value: "assumed_jst",
      projectAdoptionStatus: "provisional",
    },
    relatedSourceClaimIds: [
      "source-claim.ptna-2017.getsumei-boundary-example.v1",
      "source-claim.getsumei-time-basis-variants.v1",
    ],
    prohibitedResolution: [
      "assumed_jstを唯一のsource truthと呼ばない。",
      "自然時補正を推測実装しない。",
      "経度、DST、真太陽時、均時差を補完しない。",
      "conflictを解消済みにしない。",
    ],
  },
] as const satisfies readonly ConflictRecord[];

export const personalStarImplementationObservations = [
  { observationId: "observation.personal.daily-master-days.v1", implementationBindingId: "implementation.personal.daily-master.v1", status: "implementation_observed", summary: "1900〜2050年のdaily master 55,152日を観測した。", counts: { dailyMasterDays: 55_152 }, unresolvedIssues: [] },
  { observationId: "observation.personal.risshun-boundaries.v1", implementationBindingId: "implementation.personal.daily-master.v1", status: "implementation_observed", summary: "立春151件のdaily master年星切替を観測した。", counts: { officialEvents: 151, sameDaySwitch: 150, nextDaySwitch: 1, missing: 0 }, unresolvedIssues: ["1900年立春の翌日切替理由は未解決。"] },
  { observationId: "observation.personal.setsuiri-boundaries.v1", implementationBindingId: "implementation.personal.daily-master.v1", status: "implementation_observed", summary: "節入り1,812件のdaily master月星切替を観測した。", counts: { officialEvents: 1_812, sameDaySwitch: 1_806, nextDaySwitch: 6, missing: 0 }, unresolvedIssues: ["翌日切替6件の理由は未解決。"] },
] as const satisfies readonly ImplementationObservation[];

export const personalStarVerificationRecords = [
  { verificationId: "verification.personal.honmei-year-cycle.v1", subjectIds: ["rule.personal.year-nine-star-cycle.v1"], verificationVersion: "1", status: "verified", actual: 9, expected: 9, unit: "annual cycle fixtures", notes: [] },
  { verificationId: "verification.personal.honmei-risshun-boundaries-151.v1", subjectIds: ["boundary.honmei-risshun-timestamp.v1"], verificationVersion: "1", status: "implementation_observed", actual: 151, expected: 151, unit: "Risshun observations", notes: ["150 same-day, 1 next-day, 0 missing"] },
  { verificationId: "verification.personal.getsumei-source-table-36.v1", subjectIds: ["source-claim.jingukan-1935.monthly-nine-star-36.v1"], verificationVersion: "1", status: "verified", actual: 36, expected: 36, unit: "source table values", notes: [] },
  { verificationId: "verification.personal.getsumei-regression-36.v1", subjectIds: ["lookup.personal.getsumei-36.v1"], verificationVersion: "1", status: "verified", actual: 36, expected: 36, unit: "regression values", notes: [] },
  { verificationId: "verification.personal.getsumei-inputs-108.v1", subjectIds: ["getsumei-star-resolution"], verificationVersion: "1", status: "verified", actual: 108, expected: 108, unit: "annual stars by Setsu months", notes: ["36値へ集約"] },
  { verificationId: "verification.personal.daily-master-days.v1", subjectIds: ["implementation.personal.daily-master.v1"], verificationVersion: "1", status: "implementation_observed", actual: 55_152, expected: 55_152, unit: "daily rows", notes: [] },
  { verificationId: "verification.personal.setsuiri-boundaries-1812.v1", subjectIds: ["boundary.personal-daily-master-resolution.v1"], verificationVersion: "1", status: "implementation_observed", actual: 1_812, expected: 1_812, unit: "Setsuiri observations", notes: ["1,806 same-day, 6 next-day, 0 missing"] },
  { verificationId: "verification.personal.tomihisa-role-article.v1", subjectIds: ["source-claim.tomihisa-institutional.getsumei-personal-role.v1"], verificationVersion: "1", status: "partially_confirmed", actual: 1, expected: 1, unit: "institutional specialist article claim", notes: [] },
  { verificationId: "verification.personal.tomihisa-keisha-table.v1", subjectIds: ["source-claim.tomihisa-institutional.getsumei-keisha-table.v1"], verificationVersion: "1", status: "partially_confirmed", actual: 108, expected: 108, unit: "article table inputs", notes: ["傾斜RuleはHOLD"] },
] as const satisfies readonly VerificationRecord[];

export const personalStarImplementationGaps = [
  { implementationGapId: "gap.personal.honmei-2026-risshun-pre-boundary.v1", status: "open", summary: "2026立春当日の時刻前はsource/project候補が旧年星2だが、current daily masterは新年星1を終日返す。", relatedBoundaryRuleIds: ["boundary.honmei-risshun-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], prohibitedActions: ["productionを変更しない。", "daily masterをexact resultと呼ばない。"] },
  { implementationGapId: "gap.personal.getsumei-2026-shosho-pre-boundary.v1", status: "open", summary: "2026小暑当日の時刻前はsource/project候補が午月星4だが、current daily masterは未月星3を終日返す。", relatedBoundaryRuleIds: ["boundary.getsumei-setsuiri-timestamp.v1", "boundary.personal-daily-master-resolution.v1"], prohibitedActions: ["productionを変更しない。", "exact timestamp完全確認済みと記録しない。"] },
] as const satisfies readonly ImplementationGap[];

export const personalStarConceptRelations = [
  { left: "yearKyusei", right: "annualPlateCenterStar", valueRelation: "same_value", conceptRelation: "same_concept", techniqueMerge: "allowed_only_for_period_value" },
  { left: "annualPlateCenterStar", right: "honmeiStar", valueRelation: "same_value", conceptRelation: "derived_personal_attribute", roleRelation: "distinct_role", techniqueMerge: "prohibited" },
  { left: "monthKyusei", right: "monthlyPlateCenterStar", valueRelation: "same_value", conceptRelation: "same_concept", techniqueMerge: "allowed_only_for_period_value" },
  { left: "monthlyPlateCenterStar", right: "getsumeiStar", valueRelation: "same_value", conceptRelation: "derived_personal_attribute", roleRelation: "distinct_role", sharedLookup: "allowed", sharedRule: "allowed", techniqueMerge: "prohibited" },
  { left: "monthKyusei", right: "getsumeiStar", valueRelation: "same_value", conceptRelation: "same_value_distinct_role", techniqueMerge: "prohibited" },
] as const;
